CREATE SCHEMA PATHFINDER;

CREATE TABLE PATHFINDER.NODES
(
	NODE_ID BIGINT NOT NULL PRIMARY KEY, 
	NODE_NAME VARCHAR(50) NOT NULL, 
	CITY VARCHAR(30) NOT NULL, 
	ZIP_CODE INTEGER,
	LATITUDE FLOAT NOT NULL,
	LONGITUDE FLOAT NOT NULL,
	HEURISTICS FLOAT
);

CREATE TABLE PATHFINDER.EDGES
(
	EDGE_ID BIGINT NOT NULL PRIMARY KEY,
	EDGE_NAME VARCHAR(30) NOT NULL,
	FROM_CROSSROADS_ID BIGINT NOT NULL,
	TO_CROSSROADS_ID BIGINT NOT NULL, 
	DISTANCE INTEGER
);

CREATE TABLE PATHFINDER.GRAPH
(
	GRAPH_CONNECTION_ID BIGINT NOT NULL PRIMARY KEY, 
	MAP_ID INTEGER NOT NULL,
	NODE_ID BIGINT NOT NULL,
	EDGE_ID BIGINT NOT NULL, 
	FOREIGN KEY(NODE_ID) REFERENCES PATHFINDER.NODES (NODE_ID),
	FOREIGN KEY(EDGE_ID) REFERENCES PATHFINDER.EDGES (EDGE_ID)
);

DROP TABLE PATHFINDER.GRAPH CASCADE;
DROP TABLE PATHFINDER.EDGES CASCADE;
DROP TABLE PATHFINDER.NODES CASCADE;
	