DROP DATABASE PATHFINDER;
CREATE DATABASE PATHFINDER;

CREATE TABLE PATHFINDER.NODES
(
	NODE_ID BIGINT NOT NULL PRIMARY KEY, 
	NODE_NAME VARCHAR(50) NOT NULL, 
	CITY VARCHAR(30) NOT NULL, 
	ZIP_CODE INTEGER,
	LATITUDE FLOAT NOT NULL,
	LONGITUDE FLOAT NOT NULL,
	HEURISTICS FLOAT
);

CREATE TABLE PATHFINDER.EDGES
(
	EDGE_ID BIGINT NOT NULL PRIMARY KEY,
	EDGE_NAME VARCHAR(30) NOT NULL,
	FROM_ID BIGINT NOT NULL,
	TO_ID BIGINT NOT NULL,
	DISTANCE INTEGER,
	FOREIGN KEY (FROM_ID) REFERENCES PATHFINDER.NODES(NODE_ID),
	FOREIGN KEY (TO_ID) REFERENCES PATHFINDER.NODES(NODE_ID)
);
ALTER TABLE PATHFINDER.EDGES MODIFY COLUMN DISTANCE FLOAT;

DROP TABLE PATHFINDER.EDGES CASCADE;
DROP TABLE PATHFINDER.NODES CASCADE;
